@LibraryApi_HostAddress = http://localhost:5092

POST {{LibraryApi_HostAddress}}/api/books
Content-Type: application/json

{
    "title": "Dune",
    "publicationYear": 1210
}

###

PUT {{LibraryApi_HostAddress}}/api/books/3
Content-Type: application/json

{
    "title": "Duneh Messiah",
    "publicationYear": 1169
}

###


DELETE  {{LibraryApi_HostAddress}}/api/books/3

###