@LibraryApi_HostAddress = http://localhost:5092

POST {{LibraryApi_HostAddress}}/api/books
Content-Type: application/json

{
    "title": "Demons",
    "publicationYear": 1654
}

###

PUT {{LibraryApi_HostAddress}}/api/books/3
Content-Type: application/json

{
    "title": "Demons",
    "publicationYear": 1654
}

###


DELETE  {{LibraryApi_HostAddress}}/api/books/1

###