@LibraryApi_HostAddress = http://localhost:5092

POST {{LibraryApi_HostAddress}}/api/books
Content-Type: application/json

{
    "id": 3,
    "title": "Dune",
    "publicationYear": 1965
}

###

PUT {{LibraryApi_HostAddress}}/api/books/3
Content-Type: application/json

{
    "id": 3,
    "title": "Duneh Messiah",
    "publicationYear": 1969
}

###


DELETE  {{LibraryApi_HostAddress}}/api/books/3

###